[package]
name = "teximage2d"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A library for working with graphics textures and compile-time embedding."

[dependencies]
stb_image = "0.2.2"
