[package]
name = "teximage2d"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A library for working with graphics textures and compile-time binary embedding."


[dependencies]
texture = { path = "texture/" }
