[package]
name = "texture_gen"
version = "0.1.4"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "Code generator for TexImage2D objects."


[dependencies]
texture = { path = "../texture" }
