[package]
name = "texture"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A crate for working with texture images."


[dependencies]
stb_image = "0.2.2"
